# Generated by Django 5.0 on 2024-01-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_address_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
