# Generated by Django 5.0 on 2024-01-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default='00001', max_length=15),
        ),
    ]
