# Generated by Django 5.0 on 2024-01-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='null@null.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
