# Generated by Django 5.0 on 2024-01-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_profile_address_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@exacmple.com', max_length=254),
        ),
    ]
