# Generated by Django 5.0 on 2024-01-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(default=10000, max_length=15),
        ),
    ]
